Cms.WebMvc/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;

namespace Cms.WebMvc.Controllers
{
  public class AppointmentController : Controller
  {
    public IActionResult Index()
    {
      return View();
    }
  }
}

Cms.WebMvc/Controllers/CategoryController.cs
using Cms.Services.Abstract;
using Cms.Shared.Utilities.Results.Complex_Types;
using Microsoft.AspNetCore.Mvc;

namespace Cms.WebMvc.Controllers
{
  public class CategoryController : Controller
  {
    private readonly ICategoryService _categoryService;

    public CategoryController(ICategoryService categoryService)
    {
      _categoryService = categoryService;
    }
    public async Task<IActionResult> Index()
    {
      var result = await _categoryService.GetAllByNonDeleted();
      if (result.ResultStatus == ResultStatus.Success)
      {
        return View(result.Data);
      }
      return View();
    }
  }
}

Cms.WebMvc/Areas/Admin/Views/Shared/_AdminCssPartial.cshtml
<link href="~/css/styles.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>

a:visited {
    color: inherit; /* Ziyaret edilmiş bağlantılar için renk ayarını değiştirme */
    text-decoration: none; /* Ziyaret edilmiş bağlantılar için alt çizgiyi kaldırma */
}

Cms.WebMvc/Areas/Admin/Views/Shared/_AdminFooter.cshtml
<footer class="py-4 bg-light mt-auto">
  <div class="container-fluid">
    <div class="d-flex align-items-center justify-content-between small">
      <div class="text-muted">Copyright &copy; CMS Hospital 2024</div>
      <div>
        <a href="#">Privacy Policy</a>
        &middot;
      </div>
    </div>
  </div>
</footer>

Cms.WebMvc/Areas/Admin/Views/Shared/_AdminJsPartial.cshtml
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
<script src="~/js/scripts.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="~/assets/demo/chart-area-demo.js"></script>
<script src="~/assets/demo/chart-bar-demo.js"></script>
<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
<script src="~/assets/demo/datatables-demo.js"></script>

Cms.WebMvc/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>@ViewBag.Title - Admin | CMS Hospital</title>
 @await Html.PartialAsync("_AdminCssPartial")
</head>
<body class="sb-nav-fixed">
  <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Index">Admin Area</a>
    <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
      <div class="input-group">
        <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
        <div class="input-group-append">
          <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
        </div>
      </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="#">Settings</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="login.html">Logout</a>
        </div>
      </li>
    </ul>
  </nav>
  <div id="layoutSidenav">
    @await Html.PartialAsync("_AdminSideBarNavPartial");
    <div id="layoutSidenav_content">
      <main>
        <div class="container-fluid">
          @RenderBody()
          </div>
      </main>
      @await Html.PartialAsync("_AdminFooter");
    </div>
  </div>
 @await Html.PartialAsync("_AdminJsPartial");
  @await RenderSectionAsync("Scripts",false);
</body>
</html>

Cms.WebMvc/Areas/Admin/Views/Shared/_AdminSideBarNavPartial.cshtml
<div id="layoutSidenav_nav">
	<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
		<div class="sb-sidenav-menu">
			<div class="nav">
				<div class="sb-sidenav-menu-heading">Dashboard</div>
				<a class="nav-link" asp-area="Admin" asp-controller="Home" asp-action="Index">
					<div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
					Dashboard
				</a>
				<a class="nav-link" asp-area="Admin" asp-controller="Admin" asp-action="Index">
					<div class="sb-nav-link-icon"><i class="fas fa-regular fa-star"></i></div>
					Admin
				</a>
				<a class="nav-link" asp-area="Admin" asp-controller="Appointment" asp-action="Index">
					<div class="sb-nav-link-icon"><i class="fas fa-solid fa-calendar-check"></i></div>
					Appointment
				</a>
				<a class="nav-link" asp-area="Admin" asp-controller="Article" asp-action="Index">
					<div class="sb-nav-link-icon"><i class="fas fa-file-alt"></i></div>
					Article
				</a>
				<a class="nav-link" asp-area="Admin" asp-controller="Category" asp-action="Index">
					<div class="sb-nav-link-icon"><i class="fas fa-th-list"></i></div>
					Category
				</a>
				<a class="nav-link" asp-area="Admin" asp-controller="Comment" asp-action="Index">
					<div class="sb-nav-link-icon"><i class="fas fa-comments"></i></div>
					Comment
				</a>
				<a class="nav-link" asp-area="Admin" asp-controller="Doctor" asp-action="Index">
					<div class="sb-nav-link-icon"><i class="fas fa-solid fa-stethoscope"></i></div>
					Doctor
				</a>
				<a class="nav-link" asp-area="Admin" asp-controller="Hospital" asp-action="Index">
					<div class="sb-nav-link-icon"><i class="fas fa-solid fa-hospital"></i></div>
					Hospital
				</a>
				<a class="nav-link" asp-area="Admin" asp-controller="User" asp-action="Index">
					<div class="sb-nav-link-icon"><i class="fas fa-users"></i></div> 
					User
				</a>
				<a class="nav-link" asp-area="Admin" asp-controller="Role" asp-action="Index">
					<div class="sb-nav-link-icon"><i class="fas fa-user-shield"></i></div>
					Role
				</a>
			</div>
		</div>
		<div class="sb-sidenav-footer">
			<div class="small">Logged in as:</div>
			Admin
		</div>
	</nav>
</div>